# Demo pipeline to conduct a Veracod Dynamic Analysis Scan (create or update)

# This Pipeline will scan my Verademo app from the Vulnerable Apps within my Demo Labs Instance
# Don't forget to do a Reset after creating the Verademo app

trigger:
#- master
- none

pool:
  vmImage: ubuntu-latest
strategy:
  matrix:
    DAST_SCAN:
      python.version: '3.7'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '$(python.version)'
  displayName: 'Setup Veracod Dynamic Analysis Scan'

- script: |
    python -m pip install --upgrade pip
    pip install -r requirements.txt
  displayName: 'Install dependencies'
  
#- script:
#    echo $(DYNAMIC_USER)
#  displayName: 'Display Variables'

#   export export JOB_NAME='$(system.teamProject)-Dynamic-Analysis'
#   export export JOB_NAME='Veracode Demo using Azure DevOps'

- script: |
    export Dynamic_Target=$(DYNAMIC_TARGET)
    export export JOB_NAME='Verademo-dotnet-0002'
    export VeraID=$(VERAID)
    export VeraPW=$(VERAPW)
    export Dynamic_User=$(DYNAMIC_USER)
    export Dynamic_Pass=$(DYNAMIC_PASS)
    python create-or-update-da-scan.py
  displayName: 'Create or update and run the Dynamic Analysis'
#    export JOB_NAME='$(system.teamProject)_ADO_yaml'